### PR TITLE
Show finish-args

### LINKED ISSUE #5: Allow showing finish-args if specified
Some modules requires special `finish-args` being set and won't work properly without them, so it would be helpful if we could also show these info if specified in the json file.

For example, `gst-libav` requires setting `GST_PLUGIN_PATH_1_0` environment path so that the app can detect the compiled module:

```yaml
finish-args:
  - '--socket=pulseaudio'
  - '--env=GST_PLUGIN_PATH_1_0=/app/lib/gstreamer-1.0' # this is necessary
modules:
  - name: gst-libav
    buildsystem: meson
    sources:
      - type: archive
        url: https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.18.5.tar.xz
        sha256: 822e008a910e9dd13aedbdd8dc63fedef4040c0ee2e927bab3112e9de693a548
```

The current design of `public/modules.json` is just allowing to specify the section under `modules` and not allowing to specify `finish-args` which is the same hierarchy with `modules` section.

### PR DESCRIPTION
**Pull request by ryonakano**
I'm noob at json formats so testing if this make finish-args appear

Closes #5

### CODE REVIEW

**Comment by ryonakano** [comment]
It does appear but `finish-args` should be out of the `modules` section so this is not valid, closing.

**Comment by dar5hak** [comment]
We could make it parallel to modules and change the JS code to check if it exists.

**Comment by ryonakano** [comment]
@dar5hak Hi sorry for making the PR noisy but I'm reallllllly noob at the backend of this web app 😅
Would you create a proper fix in/out of this PR?

**Comment by dar5hak** [comment]
@ryonakano Yes, no problem. I'll give it a shot in a few hours. Thank you for the effort. ✌️

**Comment by dar5hak** [comment]
Can't make it today. I'll try tomorrow.

**Comment by dar5hak** [comment]
@ryonakano Can you ~pull and run the updated branch~ open the Vercel preview and verify if this is what you wanted to achieve?

**Comment by ryonakano** [comment]
Hi @dar5hak, thank you for your work, looks good!

Just one tiny request is, it would be great if `finish-args` comes before `module` like the actual notation of Flatpak yaml files:

https://github.com/ryonakano/pinit/blob/2a0c19b06aa3fc11fe5b79bba8da0b7f21a09291/com.github.ryonakano.pinit.yml#L6-L18

Also, there seems to be a regression that selecting the version of components now won't switch to the module file for the selected version, and always the one for latest version is used.

with `main` branch:

https://user-images.githubusercontent.com/26003928/147359049-dc107853-8a01-4b72-91b7-b774020485d1.mov

with this branch:

https://user-images.githubusercontent.com/26003928/147359060-a2c65dae-bba9-4cf0-9c98-e4b9d2dc675e.mov

**Comment by dar5hak** [comment]
All done! I'm merging this, but feel free to reopen if you think something is missing.

**Comment by ryonakano** [comment]
Perfect! Thank you for your work! 🎉

**Pull request merged**
